#!/usr/bin/env python3

import sys

installation_msg = """
This python module does not have any requirements. You should be good to go!
"""

print(installation_msg)

sys.exit(0) # success!

# sys.exit(1) # fail!
